services:
  # Backend authentication service
  auth-service:
    build:
      context: ./Backend/services/auth_service
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=sqlite:///./auth.db
    volumes:
      - auth_data:/app/auth.db
    networks:
      - app-network

  # Frontend React application
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app-network

volumes:
  auth_data:

networks:
  app-network: 